[build]
  # Build command untuk Vite
  command = "npm run build"
  
  # Directory hasil build
  publish = "dist"
  
  # Functions directory untuk serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects dan rewrites
[[redirects]]
  # API routes ke functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  # SPA routing - semua route ke index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Headers untuk CORS dan security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Function configuration
[functions]
  # Directory untuk functions
  directory = "netlify/functions"
  
  # Runtime settings
  node_bundler = "esbuild"
  
  # Timeout untuk functions (max 15 detik di free plan)
  timeout = 15
